SITES = [
    "https://test1.com",
    "https://test2.com",
    "https://test3.com",
    "https://test4.com",
    "https://test5.com",
    "https://test6.com",
    "https://test7.com",
    "Your Name",
    "Your Name",
    "Your Name",
    "Your Name",
    "Your Name",
    "Your Name",
]
